name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      #run: docker pull juliennoblet/download-geofabrik:v2.5.0 && docker run --rm -v $PWD:/data juliennoblet/download-geofabrik download --osm.pbf shikoku
      run: export aria=chubu && wget https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_386 -O yq && chmod +x yq && wget https://github.com/julien-noblet/download-geofabrik/releases/download/v2.5.0/download-geofabrik_2.5.0_Linux_x86_64.tar.gz && tar vxfz ./download-geofabrik_2.5.0_Linux_x86_64.tar.gz && ./download-geofabrik download $aria && git clone https://github.com/openmaptiles/openmaptiles.git -b v3.12.2 && cd openmaptiles && sed -i -e 's/MAX_ZOOM=7/MAX_ZOOM=14/' .env && sed -i '397,398d' Makefile && sed -i "397i\    \$(DOCKER_COMPOSE) run \$(DC_OPTS) openmaptiles-tools psql.sh -v ON_ERROR_STOP=1 -P pager=off -c \"CREATE or REPLACE FUNCTION osml10n_geo_translit(name text, place geometry DEFAULT NULL) RETURNS TEXT AS ' BEGIN IF (place IS NULL) THEN return osml10n_cc_transscript(name,''aq''); ELSE return(osml10n_cc_transscript(name,NULL)); END IF; END; ' LANGUAGE plpgsql STABLE;\"" Makefile && sed -i "398i\    \$(DOCKER_COMPOSE) run \$(DC_OPTS) openmaptiles-tools sh -c 'pgwait && import-sql' | awk -v s=\": WARNING:\" '1{print; fflush()} \$\$0~s{print \"\\\n*** WARNING detected, aborting\"; exit(1)}'" Makefile && mkdir -p data && cp ../$aria.osm.pbf ./data && sudo cp ~/work/jp_shikoku_opentilemap/jp_shikoku_opentilemap/my-postgres.conf ./ && ../yq e -i '.services.postgres.volumes += ["./my-postgres.conf:/etc/postgresql/postgresql.conf"]' docker-compose.yml && ../yq e -i '.services.postgres.command |= "postgres -c config_file=/etc/postgresql/postgresql.conf"' docker-compose.yml && ./quickstart.sh $aria
      
