name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
    - id: step1
      run: wget https://github.com/julien-noblet/download-geofabrik/releases/download/v2.5.0/download-geofabrik_2.5.0_Linux_x86_64.tar.gz
    - id: step2
      run: tar vxfz ./download-geofabrik_2.5.0_Linux_x86_64.tar.gz
    - id: step3
      run: ./download-geofabrik download shikoku
