name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker pull juliennoblet/download-geofabrik:v2.5.0 && docker run --rm -v $PWD:/data juliennoblet/download-geofabrik download --osm.pbf shikoku
